### ISSUE TITLE
Wrong credits on this morning challenge?

### ISSUE THREAD

**Issue by mantagen** [RhodesPeter/waterfall-function-workshop#1]
I'm pretty sure this waterfall challenge was originally @des-des rather than Bes's?

https://github.com/des-des/morning-challenges/blob/master/waterfall.js

**Comment by RhodesPeter** [comment]
Thank you @mantagen. Is this correct @des-des?

**Comment by RhodesPeter** [comment]
All changed, thank you @mantagen 😀
